BEGIN TRANSACTION;
CREATE TABLE "SearchResultsAgendaHTMLURLs" (
	id INTEGER NOT NULL, 
	"AgendaHTMLiFrameURL" TEXT, 
	"PageURL" TEXT, 
	PRIMARY KEY (id)
);
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(1,'agview.aspx?agviewmeetid=1927&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=1927&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(2,'agview.aspx?agviewmeetid=2407&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2407&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(3,'agview.aspx?agviewmeetid=2147&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2147&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(4,'agview.aspx?agviewmeetid=2154&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2154&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(5,'agview.aspx?agviewmeetid=2409&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2409&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(6,'agview.aspx?agviewmeetid=2211&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2211&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(7,'agview.aspx?agviewmeetid=2181&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2181&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(8,'agview.aspx?agviewmeetid=2484&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2484&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(9,'agview.aspx?agviewmeetid=2412&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2412&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(10,'agview.aspx?agviewmeetid=2411&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2411&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(11,'agview.aspx?agviewmeetid=2216&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2216&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(12,'agview.aspx?agviewmeetid=2362&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2362&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(13,'agview.aspx?agviewmeetid=2487&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2487&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(14,'agview.aspx?agviewmeetid=2410&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2410&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(15,'agview.aspx?agviewmeetid=2361&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2361&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(16,'agview.aspx?agviewmeetid=2214&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2214&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(17,'agview.aspx?agviewmeetid=2143&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2143&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(18,'agview.aspx?agviewmeetid=2213&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2213&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(19,'agview.aspx?agviewmeetid=2221&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2221&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(20,'agview.aspx?agviewmeetid=2151&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2151&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(21,'agview.aspx?agviewmeetid=2219&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2219&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(22,'agview.aspx?agviewmeetid=2121&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2121&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(23,'agview.aspx?agviewmeetid=2364&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2364&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(24,'agview.aspx?agviewmeetid=2360&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2360&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(25,'agview.aspx?agviewmeetid=2408&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2408&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(26,'agview.aspx?agviewmeetid=2204&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2204&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(27,'agview.aspx?agviewmeetid=2275&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2275&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(28,'agview.aspx?agviewmeetid=2224&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2224&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(29,'agview.aspx?agviewmeetid=2363&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2363&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(30,'agview.aspx?agviewmeetid=2405&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2405&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(31,'agview.aspx?agviewmeetid=2349&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2349&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(32,'agview.aspx?agviewmeetid=2404&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2404&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(33,'agview.aspx?agviewmeetid=2218&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2218&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(34,'agview.aspx?agviewmeetid=2290&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2290&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(35,'agview.aspx?agviewmeetid=2285&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2285&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(36,'agview.aspx?agviewmeetid=2206&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2206&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(37,'agview.aspx?agviewmeetid=2284&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2284&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(38,'agview.aspx?agviewmeetid=1897&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=1897&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(39,'agview.aspx?agviewmeetid=2149&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2149&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(40,'agview.aspx?agviewmeetid=2229&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2229&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(41,'agview.aspx?agviewmeetid=2230&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2230&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(42,'agview.aspx?agviewmeetid=2237&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2237&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(43,'agview.aspx?agviewmeetid=2176&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2176&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(44,'agview.aspx?agviewmeetid=2245&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2245&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(45,'agview.aspx?agviewmeetid=2495&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2495&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(46,'agview.aspx?agviewmeetid=2236&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2236&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(47,'agview.aspx?agviewmeetid=2267&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2267&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(48,'agview.aspx?agviewmeetid=2397&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2397&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(49,'agview.aspx?agviewmeetid=2150&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2150&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(50,'agview.aspx?agviewmeetid=2178&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2178&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(51,'agview.aspx?agviewmeetid=2266&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2266&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(52,'agview.aspx?agviewmeetid=2139&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2139&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(53,'agview.aspx?agviewmeetid=2268&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2268&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(54,'agview.aspx?agviewmeetid=2227&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2227&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(55,'agview.aspx?agviewmeetid=2274&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2274&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(56,'agview.aspx?agviewmeetid=2269&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2269&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(57,'agview.aspx?agviewmeetid=2273&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2273&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(58,'agview.aspx?agviewmeetid=2281&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2281&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(59,'agview.aspx?agviewmeetid=2413&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2413&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(60,'agview.aspx?agviewmeetid=2226&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2226&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(61,'agview.aspx?agviewmeetid=2270&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2270&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(62,'agview.aspx?agviewmeetid=2283&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2283&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(63,'agview.aspx?agviewmeetid=2279&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2279&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(64,'agview.aspx?agviewmeetid=2442&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2442&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(65,'agview.aspx?agviewmeetid=2282&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2282&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(66,'agview.aspx?agviewmeetid=2447&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2447&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(67,'agview.aspx?agviewmeetid=2446&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2446&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(68,'agview.aspx?agviewmeetid=2439&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2439&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(69,'agview.aspx?agviewmeetid=2483&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2483&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(70,'agview.aspx?agviewmeetid=2406&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2406&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(71,'agview.aspx?agviewmeetid=2292&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2292&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(72,'agview.aspx?agviewmeetid=2271&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2271&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(73,'agview.aspx?agviewmeetid=2438&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2438&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(74,'agview.aspx?agviewmeetid=2431&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2431&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(75,'agview.aspx?agviewmeetid=2452&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2452&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(76,'agview.aspx?agviewmeetid=2424&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2424&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(77,'agview.aspx?agviewmeetid=2480&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2480&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(78,'agview.aspx?agviewmeetid=2486&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2486&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(79,'agview.aspx?agviewmeetid=2347&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2347&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(80,'agview.aspx?agviewmeetid=2233&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2233&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(81,'agview.aspx?agviewmeetid=2316&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2316&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(82,'agview.aspx?agviewmeetid=2326&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2326&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(83,'agview.aspx?agviewmeetid=2479&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2479&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(84,'agview.aspx?agviewmeetid=2398&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2398&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(85,'agview.aspx?agviewmeetid=2272&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2272&doctype=AGENDA');
INSERT INTO SearchResultsAgendaHTMLURLs VALUES(86,'agview.aspx?agviewmeetid=2333&agviewdoctype=AGENDA','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2333&doctype=AGENDA');
CREATE TABLE "SearchResultsTable" (
	id INTEGER NOT NULL, 
	"MeetingName" TEXT, 
	"Date" TEXT, 
	"Time" TEXT, 
	"Contact" TEXT, 
	"PageURL" TEXT, 
	"AgendaHTML" TEXT, 
	"AgendaPDF" TEXT, 
	"ActionSummaryHTML" TEXT, 
	"ActionSummaryPDF" TEXT, 
	"MinutesHTML" TEXT, 
	"MinutesPDF" TEXT, 
	"VideoLink" TEXT, 
	PRIMARY KEY (id)
);
INSERT INTO SearchResultsTable VALUES(1,'Information Technology Sub-Committee','2012-Jun-18','9:30 AM','Melody Duffenais613-580-2424 x20113
                Email: Melody.Duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=1927&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=2491','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=1927&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=2491','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=1927&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=2491','');
INSERT INTO SearchResultsTable VALUES(2,'Environment Committee','2012-Jun-19','9:30 AM','no contact','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2407&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3995','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2407&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3995','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2407&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3995','');
INSERT INTO SearchResultsTable VALUES(3,'Transit Commission','2012-Jun-20','9:30 AM','Melody Duffenais613-580-2424 x20113
                Email: melody.duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2147&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3599','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2147&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3599','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2147&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3599','');
INSERT INTO SearchResultsTable VALUES(4,'Community and Protective Services Committee','2012-Jun-21','9:30 AM','Marc Desjardins613-580-2424 x28821
                Email: Marc.Desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2154&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=2523','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2154&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=2523','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2154&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=2523','');
INSERT INTO SearchResultsTable VALUES(5,'Ottawa Built Heritage Advisory Committee','2012-Jun-21','9:30 AM','no contact','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2409&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4015','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2409&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4015','');
INSERT INTO SearchResultsTable VALUES(6,'Agriculture and Rural Affairs Committee','2012-Jun-25','9:30 AM','Marc Desjardins613 580 2424 ext 28821
                Email: Marc.Desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2211&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=2552','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2211&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=2552','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2211&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=2552','');
INSERT INTO SearchResultsTable VALUES(7,'Planning Committee','2012-Jun-26','9:30 AM','Christopher Zwierzchowski613-580-2424 x-21359
                Email: Christopher.Zwierzchowski@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2181&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4066','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2181&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4066','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2181&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4066','');
INSERT INTO SearchResultsTable VALUES(8,'City Council','2012-Jun-27','9:30 AM','Dawn Whelan613-580-2424 x 25639
                Email: Dawn.Whelan@Ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2484&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4528','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2484&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4528','');
INSERT INTO SearchResultsTable VALUES(9,'Finance and Economic Development Committee','2012-Jul-03','9:30 AM','Diane Blais613-580-2424 x28091
                Email: Diane.Blais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2412&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4057','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2412&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4057','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2412&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4057','');
INSERT INTO SearchResultsTable VALUES(10,'Transportation Committee','2012-Jul-04','9:30 AM','Rosemary Theriault613-580-2424 x21624
                Email: Rosemary.Theriault@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2411&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4044','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2411&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4044','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2411&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4044','');
INSERT INTO SearchResultsTable VALUES(11,'Finance and Economic Development Committee','2012-Jul-06','9:30 AM','Diane Blais613-580-2424, ext. 28091
                Email: Diane.Blais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2216&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4035','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2216&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4035','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2216&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4035','');
INSERT INTO SearchResultsTable VALUES(12,'Planning Committee','2012-Jul-09','9:30 AM','Christopher Zwierzchowski613-580-2424 x 21359
                Email: Christopher.Zwierzchowski@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2362&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3823','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2362&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3823','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2362&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3823','');
INSERT INTO SearchResultsTable VALUES(13,'City Council','2012-Jul-11','10:00 AM','Dawn Whelan613-580-2424 x 21837
                Email: dawn.whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2487&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4603','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2487&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4603','');
INSERT INTO SearchResultsTable VALUES(14,'Ottawa Built Heritage Advisory Committee','2012-Aug-02','6:00 PM','Kelly Sammon613-580-2424 x16875
                Email: Kelly.Sammon@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2410&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4032','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2410&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4032','');
INSERT INTO SearchResultsTable VALUES(15,'Planning Committee','2012-Aug-23','9:30 AM','Christopher Zwierzchowski613-580-2424 x21359
                Email: Christopher.Zwierzchowski@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2361&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3801','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2361&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3801','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2361&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3801','');
INSERT INTO SearchResultsTable VALUES(16,'Transit Commission','2012-Aug-24','9:30 AM','Melody Duffenais(613)-580-2424 ext./poste 20113
                Email: melody.duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2214&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3912','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2214&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3912','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2214&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3912','');
INSERT INTO SearchResultsTable VALUES(17,'Finance and Economic Development Committee','2012-Aug-27','9:30 AM','Diane Blais613-580-2424, ext. 28091
                Email: Diane.Blais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2143&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4028','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2143&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4028','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2143&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4028','');
INSERT INTO SearchResultsTable VALUES(18,'Environment Committee','2012-Aug-28','9:30 AM','Carole Legault613-580-2424 x28934
                Email: carolea.legault@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2213&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4010','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2213&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4010','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2213&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4010','');
INSERT INTO SearchResultsTable VALUES(19,'Debenture Committee','2012-Aug-28','10:00 AM','Joel Monfils613-580-2424 x26837
                Email: joel.monfils@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2221&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4005','','','','','');
INSERT INTO SearchResultsTable VALUES(20,'City Council','2012-Aug-29','10:00 AM','Dawn Whelan21837
                Email: dawn.whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2151&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4056','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2151&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4056','');
INSERT INTO SearchResultsTable VALUES(21,'Finance and Economic Development Committee','2012-Aug-30','9:30 AM','Diane Blais613-580-2424, ext. 16760
                Email: Diane.Blais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2219&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4003','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2219&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4003','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2219&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4003','');
INSERT INTO SearchResultsTable VALUES(22,'Transportation Committee','2012-Sep-05','9:30 AM','Melody Duffenais613-580-2424 x20113
                Email: Melody.Duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2121&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=2951','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2121&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=2951','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2121&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=2951','');
INSERT INTO SearchResultsTable VALUES(23,'Agriculture and Rural Affairs Committee','2012-Sep-06','9:30 AM','Marc Desjardins613-580-2424 x28821
                Email: Marc.Desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2364&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3855','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2364&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3855','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2364&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3855','');
INSERT INTO SearchResultsTable VALUES(24,'Planning Committee','2012-Sep-11','9:30 AM','Christopher Zwierzchowski613-580-2424 x 21359
                Email: Christopher.Zwierzchowski@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2360&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3784','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2360&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3784','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2360&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3784','');
INSERT INTO SearchResultsTable VALUES(25,'City Council','2012-Sep-12','9:30 AM','Dawn Whelan613-5802-2424 x21837
                Email: Dawn.Whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2408&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3999','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2408&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3999','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2408&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3999','');
INSERT INTO SearchResultsTable VALUES(26,'Audit Sub-Committee','2012-Sep-13','9:30 AM','Diane Blais613-580-2424, ext. 28091
                Email: Diane.Blais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2204&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3969','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2204&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3969','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2204&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3969','');
INSERT INTO SearchResultsTable VALUES(27,'Information Technology Sub-Committee','2012-Sep-17','9:30 AM','Melody Duffenais613-580-2424 ext 20113
                Email: Melody.Duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2275&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3588','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2275&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3588','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2275&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3588','');
INSERT INTO SearchResultsTable VALUES(28,'Finance and Economic Development Committee','2012-Sep-19','9:30 AM','Diane Blais613-580-2424, ext. 28091
                Email: Diane.Blais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2224&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3937','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2224&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3937','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2224&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3937','');
INSERT INTO SearchResultsTable VALUES(29,'Community and Protective Services Committee','2012-Sep-20','9:30 AM','Marc Desjardins613-580-2424 x28821
                Email: Marc.Desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2363&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3840','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2363&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3840','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2363&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3840','');
INSERT INTO SearchResultsTable VALUES(30,'Ottawa Built Heritage Advisory Committee','2012-Sep-20','6:00 PM','Kelly Sammon613-580-2424 x16875
                Email: Kelly.Sammon@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2405&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3968','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2405&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3968','');
INSERT INTO SearchResultsTable VALUES(31,'Planning Committee','2012-Sep-25','9:30 AM','Christopher Zwierzchowski613-580-2424 x 21359
                Email: Christopher.Zwierzchowski@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2349&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3771','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2349&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3771','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2349&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3771','');
INSERT INTO SearchResultsTable VALUES(32,'City Council','2012-Sep-26','9:30 AM','Dawn Whelan613-580-2424 x21837
                Email: Dawn.Whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2404&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3959','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2404&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3959','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2404&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3959','');
INSERT INTO SearchResultsTable VALUES(33,'Transit Commission','2012-Sep-27','9:30 AM','Melody Duffenais613-580-2424 ext./poste 20113
                Email: melody.duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2218&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3162','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2218&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3162','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2218&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3162','');
INSERT INTO SearchResultsTable VALUES(34,'Finance and Economic Development Committee','2012-Oct-02','9:30 AM','Diane Blais613-580-2424 x28091
                Email: Diane.Balis@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2290&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3722','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2290&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3722','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2290&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3722','');
INSERT INTO SearchResultsTable VALUES(35,'Transportation Committee','2012-Oct-03','9:30 AM','Rosemary Theriault613-580-2424 x21624
                Email: Rosemary.Theriault@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2285&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3676','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2285&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3676','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2285&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3676','');
INSERT INTO SearchResultsTable VALUES(36,'Agriculture and Rural Affairs Committee','2012-Oct-04','7:00 PM','Marc Desjardins613-580-2424 x28821
                Email: Marc.Desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2206&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3250','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2206&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3250','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2206&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3250','');
INSERT INTO SearchResultsTable VALUES(37,'Planning Committee','2012-Oct-09','9:30 AM','Christopher Zwierzchowski613-580-2424 x 21359
                Email: Christopher.Zwierzchowski@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2284&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3624','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2284&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3624','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2284&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3624','');
INSERT INTO SearchResultsTable VALUES(38,'City Council','2012-Oct-10','10:00 AM','Dawn Whelan613-580-2424 x21837
                Email: Dawn.Whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=1897&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3911','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=1897&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3911','');
INSERT INTO SearchResultsTable VALUES(39,'Information Technology Sub-Committee','2012-Oct-15','9:30 AM','Melody Duffenais613-580-2424 x20113
                Email: Melody.Duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2149&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3272','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2149&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3272','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2149&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3272','');
INSERT INTO SearchResultsTable VALUES(40,'Environment Committee','2012-Oct-16','9:30 AM','no contact','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2229&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3290','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2229&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3290','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2229&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3290','');
INSERT INTO SearchResultsTable VALUES(41,'Transit Commission','2012-Oct-17','9:30 AM','no contact','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2230&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3295','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2230&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3295','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2230&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3295','');
INSERT INTO SearchResultsTable VALUES(42,'Community and Protective Services Committee','2012-Oct-18','9:30 AM','no contact','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2237&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3337','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2237&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3337','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2237&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3337','');
INSERT INTO SearchResultsTable VALUES(43,'Ottawa Built Heritage Advisory Committee','2012-Oct-18','6:00 PM','Kelly Sammon613-580-2424 x16875
                Email: Kelly.Sammon@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2176&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3935','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2176&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3935','');
INSERT INTO SearchResultsTable VALUES(44,'Planning Committee','2012-Oct-23','9:30 AM','no contact','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2245&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3393','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2245&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3393','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2245&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3393','');
INSERT INTO SearchResultsTable VALUES(45,'City Council','2012-Oct-24','10:00 AM','Dawn Whelan613-580-2424 x 21837
                Email: dawn.whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2495&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4820','','','','','');
INSERT INTO SearchResultsTable VALUES(46,'Transit Commission','2012-Oct-24','3:30 PM','Melody Duffenais613-580-2424 ext./poste 20113
                Email: melody.duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2236&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3413','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2236&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3413','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2236&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3413','');
INSERT INTO SearchResultsTable VALUES(47,'Agriculture and Rural Affairs Committee','2012-Nov-01','9:30 AM','Marc Desjardins613-580-2424 x28821
                Email: Marc.Desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2267&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3475','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2267&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3475','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2267&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3475','');
INSERT INTO SearchResultsTable VALUES(48,'Ottawa Built Heritage Advisory Committee- Special Meeting','2012-Nov-01','9:30 AM','Kelly Sammon613-580-2424 x16875
                Email: Kelly.Sammon@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2397&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3931','','','','','');
INSERT INTO SearchResultsTable VALUES(49,'Finance and Economic Development Committee','2012-Nov-06','9:30 AM','Diane Blais613-580-2424 x28091
                Email: Diane.Blais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2150&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3536','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2150&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3536','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2150&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3536','');
INSERT INTO SearchResultsTable VALUES(50,'Transportation Committee','2012-Nov-07','9:30 AM','Melody Duffenais613-580-2424 x20113
                Email: Melody.Duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2178&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3589','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2178&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3589','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2178&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3589','');
INSERT INTO SearchResultsTable VALUES(51,'Planning Committee','2012-Nov-13','9:30 AM','Christopher Zwierzchowski613-580-2424 x21359
                Email: Christopher.Zwierzchowski@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2266&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3724','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2266&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3724','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2266&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3724','');
INSERT INTO SearchResultsTable VALUES(52,'City Council','2012-Nov-14','10:00 AM','Dawn Whelan613-580-2424 x21837
                Email: Dawn.Whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2139&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3766','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2139&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3766','');
INSERT INTO SearchResultsTable VALUES(53,'Community and Protective Services Committee','2012-Nov-15','9:30 AM','Marc Desjardins613-580-2424 x28821
                Email: Marc.Desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2268&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3744','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2268&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3744','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2268&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3744','');
INSERT INTO SearchResultsTable VALUES(54,'Agriculture and Rural Affairs Committee','2012-Nov-16','9:30 AM','Marc Desjardins613 580 2424 ext 28821
                Email: marc.desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2227&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3750','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2227&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3750','','','');
INSERT INTO SearchResultsTable VALUES(55,'Information Technology Sub-Committee','2012-Nov-19','9:30 AM','Melody Duffenais613-580-2424 ext. 20113
                Email: Melody.Duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2274&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4110','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2274&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4110','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2274&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4110','');
INSERT INTO SearchResultsTable VALUES(56,'Environment Committee','2012-Nov-20','9:30 AM','Carole Legault613-580-2424 x28934
                Email: carolea.legault@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2269&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=3901','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2269&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=3901','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2269&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=3901','');
INSERT INTO SearchResultsTable VALUES(57,'Transit Commission','2012-Nov-21','9:30 AM','Melody Duffenais613-580-2424 x20113
                Email: melody.duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2273&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4123','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2273&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4123','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2273&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4123','');
INSERT INTO SearchResultsTable VALUES(58,'Planning Committee','2012-Nov-27','9:30 AM','Christopher Zwierzchowski613-580-2424 ext. 21359
                Email: Christopher.Zwierzchowski@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2281&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4103','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2281&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4103','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2281&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4103','');
INSERT INTO SearchResultsTable VALUES(59,'City Council','2012-Nov-28','10:00 AM','Dawn Whelan613-580-2424 x21837
                Email: Dawn.Whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2413&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4175','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2413&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4175','');
INSERT INTO SearchResultsTable VALUES(60,'Audit Sub-Committee','2012-Nov-29','1:30 PM','Diane Blais613-580-2424, ext. 28091
                Email: Diane.Blais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2226&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4143','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2226&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4143','','','');
INSERT INTO SearchResultsTable VALUES(61,'Finance and Economic Development Committee','2012-Dec-04','9:30 AM','Diane Blais613-580-2424 x28091
                Email: Diane.Blais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2270&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4218','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2270&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4218','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2270&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4218','');
INSERT INTO SearchResultsTable VALUES(62,'Transportation Committee','2012-Dec-05','12:00 PM','Rosemary Theriault613-580-2424 x21624
                Email: Rosemary Theriault@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2283&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4230','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2283&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4230','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2283&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4230','');
INSERT INTO SearchResultsTable VALUES(63,'Agriculture and Rural Affairs Committee','2012-Dec-06','9:30 AM','Marc Desjardins613-580-2424 x28821
                Email: marc.desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2279&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4237','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2279&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4237','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2279&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4237','');
INSERT INTO SearchResultsTable VALUES(64,'Transit Commission','2012-Dec-10','1:00 PM','Melody Duffenais613-580-2424 x20113
                Email: Melody.Duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2442&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4251','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2442&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4251','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2442&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4251','');
INSERT INTO SearchResultsTable VALUES(65,'Planning Committee','2012-Dec-11','9:30 AM','Christopher Zwierzchowski613-580-2424 x21359
                Email: Christopher.Zwierzchowski@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2282&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4259','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2282&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4259','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2282&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4259','');
INSERT INTO SearchResultsTable VALUES(66,'City Council','2012-Dec-12','10:00 AM','Delegation Registration613-580-2424 x21837 or/ou x12487
                Email: councildelegations@ottawa.ca      Dawn.Whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2447&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4265','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2447&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4265','');
INSERT INTO SearchResultsTable VALUES(67,'Court of Revision','2012-Dec-13','10:00 AM','Dawn Whelan613-580-2424 x21837
                Email: Dawn.Whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2446&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4284','','','','','');
INSERT INTO SearchResultsTable VALUES(68,'City Council','2012-Dec-19','10:00 AM','Dawn Whelan613-580-2424 x21837
                Email: Dawn.Whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2439&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4345','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2439&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4345','');
INSERT INTO SearchResultsTable VALUES(69,'Court of Revision- Resuming from the meeting of December 13, 2012','2013-Jan-09','10:00 AM','Dawn Whelan613-580-2424 x 21837
                Email: Dawn.Whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2483&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4445','','','','','');
INSERT INTO SearchResultsTable VALUES(70,'Planning Committee','2013-Jan-14','9:30 AM','Christopher Zwierzchowski613-580-2424, ext. 21359
                Email: Christopher.Zwierzchowski@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2406&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4478','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2406&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4478','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2406&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4478','');
INSERT INTO SearchResultsTable VALUES(71,'Environment Committee','2013-Jan-15','9:30 AM','Carole Legault613-580-2424 x28934
                Email: Carolea.Legault@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2292&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4485','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2292&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4485','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2292&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4485','');
INSERT INTO SearchResultsTable VALUES(72,'Transit Commission','2013-Jan-16','9:30 AM','Melody Duffenais613-580-2424, ext./poste 20113
                Email: melody.duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2271&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4492','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2271&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4492','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2271&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4492','');
INSERT INTO SearchResultsTable VALUES(73,'Community and Protective Services Committee','2013-Jan-17','9:30 AM','Marc Desjardins613 580 2424 ext 28821
                Email: marc.desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2438&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4529','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2438&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4529','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2438&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4529','');
INSERT INTO SearchResultsTable VALUES(74,'Agriculture and Rural Affairs Committee','2013-Jan-17','1:30 PM','Marc Desjardins613-580-2424 x28821
                Email: Marc.Desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2431&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4499','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2431&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4499','','','');
INSERT INTO SearchResultsTable VALUES(75,'Ottawa Built Heritage Advisory Committee','2013-Jan-17','6:00 PM','Kelly Sammon613-580-2424 ext. 16875
                Email: kelly.sammon@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2452&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4530','','','','','');
INSERT INTO SearchResultsTable VALUES(76,'Finance and Economic Development Committee','2013-Jan-21','9:30 AM','Diane Blais613-580-2424 x28091
                Email: Diane.Blais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2424&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4607','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2424&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4607','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2424&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4607','');
INSERT INTO SearchResultsTable VALUES(77,'City Council','2013-Jan-23','10:00 AM','Dawn Whelan613-580-2424 x21837
                Email: Dawn.Whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2480&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4662','','','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2480&doctype=MINUTES','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=MINUTES&folderid=4662','<img src="templates/classic/images/wmv.gif" alt="Windows Media Player" border="0">');
INSERT INTO SearchResultsTable VALUES(78,'Court of Revision- Resuming from December 13, 2012 and January 9, 2013.','2013-Jan-30','10:00 AM','Dawn Whelan613-580-2424 x21837
                Email: dawn.whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2486&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4730','','','','','');
INSERT INTO SearchResultsTable VALUES(79,'Finance and Economic Development Committee','2013-Feb-05','9:30 AM','Diane Blais613-580-2424 x28091
                Email: Diane.Blais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2347&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4742','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2347&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4742','','','<img src="templates/classic/images/wmv.gif" alt="Windows Media Player" border="0">');
INSERT INTO SearchResultsTable VALUES(80,'Transportation Committee','2013-Feb-06','9:30 AM','Rosemary Theriault(613) 580-2424 x21624
                Email: Rosemary.Theriault@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2233&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4759','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2233&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4759','','','<img src="templates/classic/images/wmv.gif" alt="Windows Media Player" border="0">');
INSERT INTO SearchResultsTable VALUES(81,'Agriculture and Rural Affairs Committee','2013-Feb-07','9:30 AM','Marc Desjardins613-580-2424 ext. 28821
                Email: marc.desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2316&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4770','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2316&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4770','','','<img src="templates/classic/images/wmv.gif" alt="Windows Media Player" border="0">');
INSERT INTO SearchResultsTable VALUES(82,'Planning Committee','2013-Feb-12','9:30 AM','Christopher Zwierzchowski613-580-2424, ext/poste 21359
                Email: christopher.zwierzchowski@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2326&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4796','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2326&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4796','','','<img src="templates/classic/images/wmv.gif" alt="Windows Media Player" border="0">');
INSERT INTO SearchResultsTable VALUES(83,'City Council','2013-Feb-13','10:00 AM','Dawn Whelan613-580-2424 x21837
                Email: Dawn.Whelan@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2479&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4855','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2479&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4855','','','<img src="templates/classic/images/wmv.gif" alt="Windows Media Player" border="0">');
INSERT INTO SearchResultsTable VALUES(84,'Environment Committee','2013-Feb-19','9:30 AM','Carole Legault613-580-2424 ext. 28934
                Email: Carolea.Legault@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2398&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4866','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2398&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4866','','','<img src="templates/classic/images/wmv.gif" alt="Windows Media Player" border="0">');
INSERT INTO SearchResultsTable VALUES(85,'Transit Commission','2013-Feb-20','9:30 AM','Melody Duffenais613-580-2424, ext./poste 20113
                Email: melody.duffenais@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2272&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4913','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2272&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4913','','','<img src="templates/classic/images/wmv.gif" alt="Windows Media Player" border="0">');
INSERT INTO SearchResultsTable VALUES(86,'Community and Protective Services Committee','2013-Feb-21','9:30 AM','Marc Desjardins613-580-2424 x28821
                Email: Marc.Desjardins@ottawa.ca','http://app05.ottawa.ca/sirepub/meetresults.aspx?view=Search&startdate=2012-Jun-18&enddate=2013-Feb-23','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2333&doctype=AGENDA','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=AGENDA&folderid=4880','http://app05.ottawa.ca/sirepub/mtgviewer.aspx?meetid=2333&doctype=SUMMARY','http://app05.ottawa.ca/sirepub/view.aspx?cabinet=published_meetings&doctype=SUMMARY&folderid=4880','','','');
COMMIT;
